<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <AssemblyName>llcom</AssemblyName>
    <ApplicationIcon>Assets\llcom.ico</ApplicationIcon>
    <RuntimeIdentifiers>win-x64;linux-x64;osx-x64;osx-arm64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\" />
    <AvaloniaResource Include="Assets\**" />
    <AvaloniaResource Include="languages\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.7" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.7" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.7" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.7" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.2.7">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.2.7" />
    <PackageReference Include="Avalonia.AvaloniaEdit" Version="11.1.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.1" />
    <PackageReference Include="SkiaSharp" Version="3.116.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="3.116.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="3.116.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.macOS" Version="3.116.1" />
    <PackageReference Include="LibUsbDotNet" Version="2.2.29" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\llcom.Core\llcom.Core.csproj" />
  </ItemGroup>
</Project>
