name: build

on:
  push:
    paths:
      - 'llcomNext/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux-arm,linux-x64,win-x86,win-x64,osx-x64
        dotnetos: [linux, win, osx]
        dotnetarch: [x86, x64, arm, arm64]
        exclude:
          - dotnetos: linux
            dotnetarch: x86
          - dotnetos: osx
            dotnetarch: x86
          - dotnetos: osx
            dotnetarch: arm
          - dotnetos: win
            dotnetarch: arm
      fail-fast: true
    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Build
        run: |
          cd llcomNext/LLCOM/
          dotnet publish -r $DOTNETOS-$DOTNETARCH --configuration Release --self-contained true -p:PublishTrimmed=true -p:TrimMode=link -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
          rm bin/Release/net10.0/$DOTNETOS-$DOTNETARCH/publish/*.pdb
          mkdir pkg
          mv bin/Release/net10.0/$DOTNETOS-$DOTNETARCH/publish/* pkg/

      - uses: actions/upload-artifact@v4
        with:
          name: llcomNext-${{ matrix.dotnetos }}-${{ matrix.dotnetarch }}
          path: llcomNext/LLCOM/pkg/
