name: build

on:
  push:
    paths:
      - 'llcomNext/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux-arm,linux-x64,win-x86,win-x64,osx-x64
        dotnetos: [linux, win, osx]
        dotnetarch: [x86, x64, arm, arm64]
        exclude:
          - dotnetos: linux
            dotnetarch: x86
          - dotnetos: osx
            dotnetarch: x86
          - dotnetos: osx
            dotnetarch: arm
          - dotnetos: win
            dotnetarch: arm
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - uses: actions/upload-artifact@v4
        with:
          name: llcomNext-${{ matrix.dotnetos }}-${{ matrix.dotnetarch }}
          path: llcomNext/LLCOM/pkg/
