name: test

on:
  push:
    paths:
      - 'llcomNext/**'
      - '.github/workflows/test.yml'
  pull_request:
    paths:
      - 'llcomNext/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: environment prepare
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-8.0
      - name: test
        run: |
          cd llcomNext
          dotnet test
